### ISSUE TITLE
Create seperate Model for Questions

### ISSUE THREAD

**Issue by emielergo** [star-jay/fobbage#40]
Nu zijn we de vragen altijd kwijt bij het verwijderen van een Quiz. Vragen kunnen hergebruiken in andere quizzen zou een groot pluspunt zijn.
Maakt het daarna ook makkelijker om in de UI quizzen samen te stellen als het ware.

**Comment by star-jay** [comment]
Vragen kunnen op user niveau. Dan kan ofwel de quiz of de ronde een collectie van vragen hebben.
Iedereen kan dan vragen maken en nieuwe quizen maken met bestaande vragen inderdaad.
